"""
AI Validation Layer Models & JSON Schemas.
"""


from pydantic import BaseModel, Field

from app.core.constants import AIValidationStatus


class AIValidationResult(BaseModel):
    """Output generated by the AI Validation Layer."""
    status: AIValidationStatus  # APPROVE, REJECT, CAUTION, UNAVAILABLE
    confidence: float = Field(ge=0.0, le=100.0)
    explanation: str
    reasoning: str = ""           # structured narrative reasoning
    risk_flags: list[str] = Field(default_factory=list)
    identified_risks: list[str] = Field(default_factory=list)
    missing_confirmations: list[str] = Field(default_factory=list)
    raw_response: str | None = None
    provider: str = "HEURISTIC"   # which AI provider produced this result
    model: str = ""               # actual model used
    fallback: list[str] = Field(default_factory=list)  # providers skipped/failed before success
    request_id: str = ""
    reason_code: str = ""         # INSUFFICIENT_BALANCE / RATE_LIMITED / TIMEOUT / etc.
    advisory_only: bool = True    # AI is advisory; never unlocks trading gates
